import os
import json
import subprocess as sp

env = Environment(ENV=os.environ)

DEPENDENCIES = json.loads(sp.check_output(["python", "get_dependencies.py"]))
for script in DEPENDENCIES:
    deps = DEPENDENCIES[script]

    # special case: fall response plots
    if script == 'plots/fall_responses.py':
        params = [
            ('G', 'A'), ('G', 'B'), ('H', 'A'), ('H', 'B'), 
            ('GH', 'A'), ('GH', 'B'), ('I', 'A')
        ]

        for version, block in params:
            target = "figures/fall_responses_{}_{}".format(version, block)
            targets = ["{}.{}".format(target, ext) for ext in ["pdf", "png"]]
            env.Command(
                targets, [script] + deps['sources'],
                "python $SOURCE --to $TARGETS --version {} --block {}".format(
                    version, block))

    # everything else
    else:
        env.Command(
            deps['targets'], [script] + deps['sources'], 
            "python $SOURCE --to $TARGETS")
